// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjATLnaryKYLhOGaOMREhiYHQeErKtSTs',
    appId: '1:362175859910:web:adc05b1ca97a58f4f0dbc7',
    messagingSenderId: '362175859910',
    projectId: 'amir-nagy-96cd6',
    authDomain: 'amir-nagy-96cd6.firebaseapp.com',
    storageBucket: 'amir-nagy-96cd6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqjGtrVDX_iuX8ss7yR5wXDaVwojoG-pU',
    appId: '1:362175859910:android:130588849f934646f0dbc7',
    messagingSenderId: '362175859910',
    projectId: 'amir-nagy-96cd6',
    storageBucket: 'amir-nagy-96cd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAJmbSNnFTcgQ30CiRKO-blTDzUJckCrc',
    appId: '1:362175859910:ios:60cd44214f616554f0dbc7',
    messagingSenderId: '362175859910',
    projectId: 'amir-nagy-96cd6',
    storageBucket: 'amir-nagy-96cd6.appspot.com',
    iosBundleId: 'com.amir.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAJmbSNnFTcgQ30CiRKO-blTDzUJckCrc',
    appId: '1:362175859910:ios:60cd44214f616554f0dbc7',
    messagingSenderId: '362175859910',
    projectId: 'amir-nagy-96cd6',
    storageBucket: 'amir-nagy-96cd6.appspot.com',
    iosBundleId: 'com.amir.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjATLnaryKYLhOGaOMREhiYHQeErKtSTs',
    appId: '1:362175859910:web:675a531393d17d4af0dbc7',
    messagingSenderId: '362175859910',
    projectId: 'amir-nagy-96cd6',
    authDomain: 'amir-nagy-96cd6.firebaseapp.com',
    storageBucket: 'amir-nagy-96cd6.appspot.com',
  );
}
